# Generated by Django 2.1.3 on 2019-02-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=200, unique=True)),
                ('video_name', models.CharField(max_length=50)),
            ],
        ),
    ]
